/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  ReactionType: "ANGRY" | "HAHA" | "LIKE" | "LOVE" | "SAD" | "WOW"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Comment: { // root type
    id: string; // ID!
    link: NexusGenRootTypes['Link']; // Link!
    reactions: Array<NexusGenRootTypes['Reaction'] | null>; // [Reaction]!
    text: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Link: { // root type
    description: string; // String!
    id: string; // ID!
    reactions: Array<NexusGenRootTypes['Reaction'] | null>; // [Reaction]!
    url: string; // String!
  }
  Mutation: {};
  Query: {};
  Reaction: { // root type
    comment?: NexusGenRootTypes['Comment'] | null; // Comment
    id: string; // ID!
    link?: NexusGenRootTypes['Link'] | null; // Link
    type: NexusGenEnums['ReactionType']; // ReactionType!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // root type
    email: string; // String!
    id: string; // ID!
    name: string; // String!
  }
}

export interface NexusGenInterfaces {
  Reactable: NexusGenRootTypes['Comment'] | NexusGenRootTypes['Link'];
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Comment: { // field return type
    id: string; // ID!
    link: NexusGenRootTypes['Link']; // Link!
    reactions: Array<NexusGenRootTypes['Reaction'] | null>; // [Reaction]!
    text: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Link: { // field return type
    description: string; // String!
    id: string; // ID!
    postedBy: NexusGenRootTypes['User']; // User!
    reactions: Array<NexusGenRootTypes['Reaction'] | null>; // [Reaction]!
    url: string; // String!
  }
  Mutation: { // field return type
    createLink: NexusGenRootTypes['Link']; // Link!
    deleteLink: NexusGenRootTypes['Link']; // Link!
    reactLink: NexusGenRootTypes['Link']; // Link!
    signIn: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    signUp: NexusGenRootTypes['AuthPayload']; // AuthPayload!
  }
  Query: { // field return type
    getFeed: NexusGenRootTypes['Link'][]; // [Link!]!
  }
  Reaction: { // field return type
    comment: NexusGenRootTypes['Comment'] | null; // Comment
    id: string; // ID!
    link: NexusGenRootTypes['Link'] | null; // Link
    type: NexusGenEnums['ReactionType']; // ReactionType!
    user: NexusGenRootTypes['User']; // User!
  }
  User: { // field return type
    email: string; // String!
    id: string; // ID!
    links: NexusGenRootTypes['Link'][]; // [Link!]!
    name: string; // String!
  }
  Reactable: { // field return type
    reactions: Array<NexusGenRootTypes['Reaction'] | null>; // [Reaction]!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Comment: { // field return type name
    id: 'ID'
    link: 'Link'
    reactions: 'Reaction'
    text: 'String'
    user: 'User'
  }
  Link: { // field return type name
    description: 'String'
    id: 'ID'
    postedBy: 'User'
    reactions: 'Reaction'
    url: 'String'
  }
  Mutation: { // field return type name
    createLink: 'Link'
    deleteLink: 'Link'
    reactLink: 'Link'
    signIn: 'AuthPayload'
    signUp: 'AuthPayload'
  }
  Query: { // field return type name
    getFeed: 'Link'
  }
  Reaction: { // field return type name
    comment: 'Comment'
    id: 'ID'
    link: 'Link'
    type: 'ReactionType'
    user: 'User'
  }
  User: { // field return type name
    email: 'String'
    id: 'ID'
    links: 'Link'
    name: 'String'
  }
  Reactable: { // field return type name
    reactions: 'Reaction'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createLink: { // args
      description: string; // String!
      url: string; // String!
    }
    deleteLink: { // args
      id: string; // String!
    }
    reactLink: { // args
      id: string; // String!
      reaction: NexusGenEnums['ReactionType']; // ReactionType!
    }
    signIn: { // args
      email: string; // String!
      password: string; // String!
    }
    signUp: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  Reactable: "Comment" | "Link"
}

export interface NexusGenTypeInterfaces {
  Comment: "Reactable"
  Link: "Reactable"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    resolveType: false
    __typename: false
    isTypeOf: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}